# Generated by Django 3.2 on 2021-04-16 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='deckId',
            new_name='deck',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='deckId',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='userId',
        ),
        migrations.AddField(
            model_name='cards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', default = 1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decks',
            name='id',
            field=models.BigAutoField(auto_created=True, default = 1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decks',
            name='user',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
