# Generated by Django 3.2 on 2021-04-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210416_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Decks',
        ),
    ]
