# Generated by Django 3.2 on 2021-04-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('registered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('deckId', models.AutoField(primary_key=True, serialize=False)),
                ('deckName', models.CharField(default='Custom Deck', max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('front', models.CharField(max_length=50, unique=True)),
                ('back', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=500)),
                ('added', models.DateTimeField()),
                ('revised', models.TimeField(auto_now_add=True)),
                ('nat_for', models.FloatField(default=0.1)),
                ('for_nat', models.FloatField(default=0.1)),
                ('deckId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.decks')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
